name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run tests
        run: go test -v

      - name: Build binaries
        run: |
          # Linux
          GOOS=linux GOARCH=amd64 go build -o wtm-linux-amd64
          GOOS=linux GOARCH=arm64 go build -o wtm-linux-arm64

          # macOS
          GOOS=darwin GOARCH=amd64 go build -o wtm-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o wtm-darwin-arm64

          # Windows
          GOOS=windows GOARCH=amd64 go build -o wtm-windows-amd64.exe
          GOOS=windows GOARCH=arm64 go build -o wtm-windows-arm64.exe

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            wtm-linux-amd64
            wtm-linux-arm64
            wtm-darwin-amd64
            wtm-darwin-arm64
            wtm-windows-amd64.exe
            wtm-windows-arm64.exe
          generate_release_notes: true
